### ISSUE TITLE
Missing UOSC

### ISSUE THREAD

**Issue by Delvaux-Jean-Baptiste** [ruyo/VRM4U#382] opened 2024-06-02 21:45 UTC
**Describe the bug**
I cannot package my game because of some missing dependency

**Screenshots, log**
------ Building 7 action(s) started ------
[1/7] Compile [x64] APCharacter.cpp
[2/7] Compile [x64] APCharacter.gen.cpp
[3/7] Compile [x64] ImprovedPerception.cpp
[4/7] Compile [x64] ImprovedPerception.init.gen.cpp
[5/7] Compile [x64] VrmVMCObject.gen.cpp
E:\UE\UE_5.4\Engine\Source\Runtime\Core\Public\Templates\PointerIsConvertibleFromTo.h(19): error C2027: use of undefined type ‘UOSCServer’
[UBA-StealthGame-Win64-Shipping.txt](https://github.com/user-attachments/files/15527003/UBA-StealthGame-Win64-Shipping.txt)

**UnrealEngine Version:**
UE 5.4.1

**Comment by ruyo** [comment] 2024-06-06 14:18
Hi.
I could not reproduce it on my end.
I took care of it just in case, so it is probably fixed in the latest version (20240606)

**Closed** 2024-06-06 17:44 UTC
