### ISSUE TITLE
Crashed when import a VRM model to UE5

### ISSUE THREAD

**Issue by Lazarus-glhf** [ruyo/VRM4U#176] opened 2022-06-03 06:32 UTC
UE5 crashed when I imported a VRM model, the project is new and empty, everything works fine on other projects and models.

Log:

Assertion failed: Pair != nullptr [File:E:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\Containers\Map.h] [Line: 656]

UnrealEditor_VRM4ULoader
UnrealEditor_VRM4ULoader
UnrealEditor_VRM4ULoader
UnrealEditor_VRM4UImporter
UnrealEditor_UnrealEd!UFactory::FactoryCreateFile() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Factories\Factory.cpp:113]
UnrealEditor_UnrealEd!UFactory::ImportObject() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Factories\Factory.cpp:205]
UnrealEditor_AssetTools!UAssetToolsImpl::ImportAssetsInternal() [D:\build\++UE5\Sync\Engine\Source\Developer\AssetTools\Private\AssetTools.cpp:2254]
UnrealEditor_AssetTools!UAssetToolsImpl::ImportAssets() [D:\build\++UE5\Sync\Engine\Source\Developer\AssetTools\Private\AssetTools.cpp:1277]
UnrealEditor_AssetTools!UAssetToolsImpl::ImportAssetsWithDialogImplementation() [D:\build\++UE5\Sync\Engine\Source\Developer\AssetTools\Private\AssetTools.cpp:3875]
UnrealEditor_AssetTools!UAssetToolsImpl::ImportAssetsWithDialogAsync() [D:\build\++UE5\Sync\Engine\Source\Developer\AssetTools\Private\AssetTools.cpp:1113]
UnrealEditor_ContentBrowserAssetDataSource!UContentBrowserAssetDataSource::OnImportClicked() [D:\build\++UE5\Sync\Engine\Plugins\Editor\ContentBrowser\ContentBrowserAssetDataSource\Source\ContentBrowserAssetDataSource\Private\ContentBrowserAssetDataSource.cpp:2125]
UnrealEditor_ContentBrowserAssetDataSource!TBaseUObjectMethodDelegateInstance<0,UContentBrowserAssetDataSource,FReply __cdecl(void),FDefaultDelegateUserPolicy,UContentBrowserToolbarMenuContext const *>::Execute() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:594]
UnrealEditor_Slate!SButton::ExecuteOnClick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Widgets\Input\SButton.cpp:464]
UnrealEditor_Slate!SButton::OnMouseButtonUp() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Widgets\Input\SButton.cpp:389]
UnrealEditor_Slate!<lambda_51e270ca99ea7ce852539efd04dd453f>::operator()() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4961]
UnrealEditor_Slate!FEventRouter::Route<FReply,FEventRouter::FToLeafmostPolicy,FPointerEvent,<lambda_51e270ca99ea7ce852539efd04dd453f> >() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:405]
UnrealEditor_Slate!FSlateApplication::RoutePointerUpEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:4947]
UnrealEditor_Slate!FSlateApplication::ProcessMouseButtonUpEvent() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5495]
UnrealEditor_Slate!FSlateApplication::OnMouseUp() [D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:5460]
UnrealEditor_ApplicationCore!FWindowsApplication::ProcessDeferredMessage() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2210]
UnrealEditor_ApplicationCore!FWindowsApplication::DeferMessage() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:2699]
UnrealEditor_ApplicationCore!FWindowsApplication::ProcessMessage() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:1078]
UnrealEditor_ApplicationCore!FWindowsApplication::AppWndProc() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsApplication.cpp:916]
user32
user32
InkObj
atlthunk
user32
user32
UnrealEditor_ApplicationCore!FWindowsPlatformApplicationMisc::PumpMessages() [D:\build\++UE5\Sync\Engine\Source\Runtime\ApplicationCore\Private\Windows\WindowsPlatformApplicationMisc.cpp:138]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5139]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:183]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:147]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:283]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:330]
UnrealEditor!__scrt_common_main_seh() [d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

UnrealEngine Version:
[UE5]

**Comment by ruyo** [comment] 2022-06-04 04:45
Hi.

If that VRM file has a shareable license, please attach it. I will check it out.
Also, if possible, please use the plugin built as a C++ project. It will output more detailed logs.
However, the procedure is complicated, so if you don't understand the above explanation, you can leave it as it is.

There doesn't seem to be any other way to find out.
VRM4U has numerous import options, so you can switch between them and test.

Thanks.

**Comment by Lazarus-glhf** [comment] 2022-06-04 12:34
I tried in C++  project and use different import options, but it seems not working. I can send the VRM file to you privately, this model is private.

**Comment by ruyo** [comment] 2022-06-06 19:19
Thanks for the C++ project log!

I found the cause of the problem.
There seems to be an inconsistency in the material's animation data specified in blendshape.
It has been fixed in the latest source.
It will be applied in the next release.

**Comment by Lazarus-glhf** [comment] 2022-06-06 19:22
Glad to hear that! I can't wait to see the next release !

**Comment by Lazarus-glhf** [comment] 2022-06-08 12:54
I think the problem is fixed! Thanks for your work!

**Closed** 2022-06-08 12:55 UTC
